name: Dismiss stale PR approvals

on:
  pull_request_target:
    types: [synchronize]
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  review_prs:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run BCR PR Review Approver
        uses: meteorcloudy/continuous-integration/actions/bcr-pr-reviewer@bcr_reviewer
        with:
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: dismiss_approvals
